<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="250" height="300"/></a>
<pre>
<center><b><h1>Data Mining</b></center>
<center><b><h1>Lab - 7 (Part 2)</b></center> 
<center><b><h1>Kavyam Joshi| 23010101114 | 21/07/2025 </b></center> 

<pre>

### Step 1: Load the Dataset
Load the `Tdata.csv` file and display the first few rows.

In [3]:
import pandas as pd


data = pd.read_csv('Tdata.csv')
data

  Transaction  bread  butter  coffee  eggs  jam  milk
0          T1      1       1       0     0    0     1
1          T2      1       1       0     0    1     0
2          T3      1       0       0     1    0     1
3          T4      1       1       0     0    0     1
4          T5      1       0       1     0    0     0
5          T6      0       0       1     1    1     0

### Step 2: Drop the 'Transaction' Column
We're only interested in the items (not the transaction IDs).

In [6]:
data_items = data.drop(columns=['Transaction'])
data_items

   bread  butter  coffee  eggs  jam  milk
0      1       1       0     0    0     1
1      1       1       0     0    1     0
2      1       0       0     1    0     1
3      1       1       0     0    0     1
4      1       0       1     0    0     0
5      0       0       1     1    1     0

### Step 3: Count Single Items
See how many transactions include each item.

In [12]:
data_items.sum()

bread     5
butter    3
coffee    2
eggs      2
jam       2
milk      3
dtype: int64

### Step 4: Define Apriori Function
This function finds frequent itemsets of size 1, 2, and 3 with minimum support.

In [39]:
from itertools import combinations

def find_frequent_itemsets(data,min_support):
    n = len(data)
    result = []
    
    for k in [1,2,3]:
         for items in combinations(data.columns,k):
             mask = data[list(items)].all(axis = 1)
             support = mask.sum() / n
             if support >= min_support:
                 result.append((frozenset(items),round(support,2)))

    return result

### Step 5: Run Apriori
Set `min_support = 0.6` and display the frequent itemsets.

In [44]:
frequent_itemsets = find_frequent_itemsets(data_items, min_support=0.5)

### Step 6 Display as a DataFrame

In [45]:
for itemsets, support in frequent_itemsets:
    print(f"{set(itemsets)} -> Support : {support}")

{'bread'} -> Support : 0.83
{'butter'} -> Support : 0.5
{'milk'} -> Support : 0.5
{'butter', 'bread'} -> Support : 0.5
{'milk', 'bread'} -> Support : 0.5

In [46]:
result_data = pd.DataFrame(frequent_itemsets, columns=['Itemset','Support'])
result_data

           Itemset  Support
0          (bread)     0.83
1         (butter)     0.50
2           (milk)     0.50
3  (butter, bread)     0.50
4    (milk, bread)     0.50

# Orange Tool : - >Generate Same Frequent Patterns in Orange tools

# Extra : - >  Define Apriori Function without itertools